### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by andrewfullard** [armankhoshnevis/RCW_Proejct#7]
Overall it looks like you have nearly everything for the project. I would like to see explicit documentation though!

**Comment by armankhoshnevis** [comment]
Thanks for the feedback.

The second rule sorted just last late night. The documentation will be provided for sure!

**Comment by armankhoshnevis** [comment]
A comprehensive documentation is now prepared and its corresponding website is ready to deploy. Please see the PR #9.
